name: GitHub Self-Updating TODAY

on:
  schedule:
    - cron: "* * * * *"

# on: [push]

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      
      - name: Check out repository code
        # https://github.com/actions/checkout/tree/v3.0.2
        uses: actions/checkout@v3
      
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
  
      - name: Modify date
        run: |
          echo "Today is ..." > README.md
          date +%Y-%m-%d >> README.md
          week=$(date +%A)
          
          echo "$week"
          
          if [ $week == 'Monday' ]; then
            echo -n "It's Monday Blue...QAQ" >> README.md
          elif [ $week == 'Tuesday' ]; then
            echo -n "Tuesdays are the days when people really get the ball rolling. Fighting!!!" >> README.md
          elif [ $week == 'Wednesday' ]; then
            echo -n "Happy Hump Day!! Here’s only two days left until the weekend!!!" >> README.md
          elif [ $week == 'Thursday' ]; then
            echo -n "Thirsty Thursday, but i don't drink..." >> README.md
          elif [ $week == 'Friday' ]; then
            echo -n "T.G.I.F. I'm in love <3" >> README.md
          elif [ $week == 'Saturday ' ]; then
            echo -n "OHHHHH~~ Happy Saturday!!! " >> README.md
          else
            echo "Lazy Sunday... I don't want to go to work tomorrow..."
          fi
          
          cat README.md
          
      - name: Push to repository
        run: |
          git config --global user.name "J-I-P"
          git config --global user.email "apple80177@gmail.com"
          now=$(date +%Y-%m-%d)
          git add -A
          git commit -m "Auto Push on $now"
          git push
          
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
