name: GitHub Self-Updating TODAY

on:
  schedule:
    - cron: "0 0 * * *"

# on: [push]

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Set timezone
        uses: MathRobin/timezone-action@v1.1
        with:
          timezoneLinux: 'Asia/Taipei'
          timezoneMacos: 'Asia/Taipei'
      
      - name: Check out repository code
        # https://github.com/actions/checkout/tree/v4
        uses: actions/checkout@v4
      
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
  
      - name: Modify date
        run: |
          today=$(date +%Y-%m-%d)
          date '+Current Date: %F%n  |  Update Time: %H:%M:%S'  > README.md
          curl 'https://wttr.in/{Taipei,Taichung}?F1qT' > today.txt
          week=$(date +%A)
          echo $week
          echo -e '\n```' >> README.md
          cat today.txt >> README.md
          echo '```' >> README.md
          
          cat README.md
          
      - name: Push to repository
        run: |
          git config --global user.name "J-I-P"
          git config --global user.email "apple80177@gmail.com"
          now=$(date +%Y-%m-%d)
          git add -A
          git commit -m "Auto Push on $now"
          git push
          
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
